// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Async = require("serbet/src/Async.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Decco = require("decco/src/Decco.js");
var Serbet = require("serbet/src/Serbet.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function params_decode(v) {
  var match = Js_json.classify(v);
  if (typeof match === "number" || match.tag !== /* JSONObject */2) {
    return Decco.error(undefined, "Not an object", v);
  } else {
    var match$1 = Decco.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(match[0], "name"), null));
    if (match$1.tag) {
      var e = match$1[0];
      return /* Error */Block.__(1, [{
                  path: ".name" + e.path,
                  message: e.message,
                  value: e.value
                }]);
    } else {
      return /* Ok */Block.__(0, [{
                  name: match$1[0]
                }]);
    }
  }
}

var endpoint = Serbet.endpoint(undefined, {
      path: "/hello/:name",
      verb: /* GET */0,
      handler: (function (req) {
          return Async.let_(Curry._1(req.requireParams, params_decode), (function (params) {
                        return Async.async(/* OkString */Block.__(3, ["Hello there, " + params.name]));
                      }));
        })
    });

var HelloEndpoint = {
  params_decode: params_decode,
  endpoint: endpoint
};

var app = Serbet.application(undefined, /* :: */[
      endpoint,
      /* [] */0
    ]);

exports.HelloEndpoint = HelloEndpoint;
exports.app = app;
/* endpoint Not a pure module */
